import { type AnyPgColumn, pgTable, uuid, text, timestamp, jsonb, index, integer, bigint, boolean } from "drizzle-orm/pg-core";
import { companies } from "./companies.js";
import { agents } from "./agents.js";
import { agentWakeupRequests } from "./agent_wakeup_requests.js";

export const heartbeatRuns = pgTable(
  "heartbeat_runs",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    companyId: uuid("company_id").notNull().references(() => companies.id),
    agentId: uuid("agent_id").notNull().references(() => agents.id),
    invocationSource: text("invocation_source").notNull().default("on_demand"),
    triggerDetail: text("trigger_detail"),
    status: text("status").notNull().default("queued"),
    startedAt: timestamp("started_at", { withTimezone: true }),
    finishedAt: timestamp("finished_at", { withTimezone: true }),
    error: text("error"),
    wakeupRequestId: uuid("wakeup_request_id").references((): AnyPgColumn => agentWakeupRequests.id),
    exitCode: integer("exit_code"),
    signal: text("signal"),
    usageJson: jsonb("usage_json").$type<Record<string, unknown>>(),
    resultJson: jsonb("result_json").$type<Record<string, unknown>>(),
    sessionIdBefore: text("session_id_before"),
    sessionIdAfter: text("session_id_after"),
    logStore: text("log_store"),
    logRef: text("log_ref"),
    logBytes: bigint("log_bytes", { mode: "number" }),
    logSha256: text("log_sha256"),
    logCompressed: boolean("log_compressed").notNull().default(false),
    stdoutExcerpt: text("stdout_excerpt"),
    stderrExcerpt: text("stderr_excerpt"),
    errorCode: text("error_code"),
    externalRunId: text("external_run_id"),
    contextSnapshot: jsonb("context_snapshot").$type<Record<string, unknown>>(),
    runType: text("run_type").notNull().default("worker"),
    rootRunId: uuid("root_run_id").references((): AnyPgColumn => heartbeatRuns.id, { onDelete: "set null" }),
    parentRunId: uuid("parent_run_id").references((): AnyPgColumn => heartbeatRuns.id, { onDelete: "set null" }),
    graphDepth: integer("graph_depth").notNull().default(0),
    verificationVerdict: text("verification_verdict"),
    repairAttempt: integer("repair_attempt").notNull().default(0),
    policySnapshotJson: jsonb("policy_snapshot_json").$type<Record<string, unknown>>(),
    artifactBundleJson: jsonb("artifact_bundle_json").$type<Record<string, unknown>>(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    companyAgentStartedIdx: index("heartbeat_runs_company_agent_started_idx").on(
      table.companyId,
      table.agentId,
      table.startedAt,
    ),
    rootRunIdx: index("heartbeat_runs_root_run_idx").on(table.rootRunId),
    parentRunIdx: index("heartbeat_runs_parent_run_idx").on(table.parentRunId),
  }),
);
